RED = '\033[31m'
END = '\033[0m'
ARG = "R50_aug"

# DATADIR = "../../PatchCore/data/"
DATADIR = "/home/kby/mnt/hdd/coffee/PatchCore/data/"
# MODELNAME = f"../../PatchCore/weights/coffee_{ARG}.pth"
MODELNAME = f"/home/kby/mnt/hdd/coffee/PatchCore/weights/coffee_{ARG}.pth"
DATASET = "coffee"
BACKBONE = "resnet50"
# THRESHOLD = 23        #WideResNet50
# THRESHOLD = 14.85          #Resnet50_aug
THRESHOLD = 19.85          #Resnet50_aug
# THRESHOLD = 9.11          #Resnet50 2,4
# THRESHOLD = 14.26          #Resnet50 2,3,4
# THRESHOLD = 54          #Effib4
DIRNAME = "/home/kby/mnt/hdd/coffee/PatchCore/coffee"
# DIRNAME = "../../PatchCore/coffee"
TRAINDIR = f"{DIRNAME}/train_"
TESTDIR = f"{DIRNAME}/test_"
RESULTDIR = f"/home/kby/mnt/hdd/coffee/PatchCore/coffee/result/"
# RESULTDIR = "../../PatchCore/coffee/result/"
HEADER = ["FileName", "Score", "Flag"]
